### ISSUE TITLE
[Suggestion] Add/remove coolants

### ISSUE THREAD

**Issue by ChiefArug** [North-West-Wind/MekanismFissionRecipe#1]
Just want to say, this is a pretty cool mod!

**__Idea:__**
Ability to remove and add coolants (and their hot variants)

Mainly so you can fix it accepting all fluids tagged `minecraft:water`, which is currently the only way to make fluids have physics and so pack makers with mods that apply this tag to get physics don't have to deal with those fluids being usable in reactors.
Also neat for making stuff like liquid starlight a custom coolant.

**Comment by North-West-Wind** [comment]
This seems cool. I'll try to work on that.

**Comment by North-West-Wind** [comment]
Added in v1.1.0
