### ISSUE TITLE
1.19.2 crashing on startup

### ISSUE THREAD

**Issue by CvoidWyvern** [North-West-Wind/MekanismFissionRecipe#10]
Forge 43.2.0 Mekanism 10.3.5 Mekanism Generators 10.3.5 Mekanism Fission Recipe 3.0.0
No other official Mekanism modules installed
[Crash](https://mclo.gs/55FbkSA)
[Latest.log](https://mclo.gs/6Hp5mkR)

**Comment by North-West-Wind** [comment]
Crash on start? Server or client or both?

**Comment by North-West-Wind** [comment]
Fixed with v3.0.1
