### ISSUE TITLE
Custom kubejs fluid coolant & Water creates steam even when the reactor is off

### ISSUE THREAD

**Issue by Xplodin** [North-West-Wind/MekanismFissionRecipe#13]
Soo I made a custom fluid coolant, and when I input the coolant into the reactor it starts producing steam despite the reactor being in the off state and not having any fuel in the reactor. this happens even on 10.3.5 and latest mek

![2023-07-12_01 52 44](https://github.com/North-West-Wind/MekanismFissionRecipe/assets/13007677/560e06a1-d857-4ab4-ac40-bb2ffb760810)
![2023-07-12_01 52 38](https://github.com/North-West-Wind/MekanismFissionRecipe/assets/13007677/ffcac76d-f870-41fa-bd3e-9c30489668a7)

**Comment by Xplodin** [comment]
this is what I have in the datapack for coolant:
{
  "type": "mekanism:fluid_coolant",
  "input": {
    "fluid": "kubejs:beanonium_fluid",
    "amount": 1
  },
  "output": {
    "gas": "mekanism:steam",
    "amount": 5
  },
  "thermalEnthalpy": 3,
  "conductivity": 1,
  "efficiency": 1
}

**Comment by Xplodin** [comment]
ignore sorry! something is wrong with my mekanism idk what but even water does the same thing

**Comment by Xplodin** [comment]
https://github.com/mekanism/Mekanism/issues/7817

this bug is with this mod and even water does the same thing

**Comment by Xplodin** [comment]
sodium works fine but water does not

**Comment by Xplodin** [comment]
Sorry for the reminder, but would love to see this fixed if possible.
This is a awesome mod that had played a part in my modpack that no longer works :(

**Comment by North-West-Wind** [comment]
Sorry for taking this long to reply. I haven't been on GitHub much lately. I will look into this issue, and hopefully publish a fix soon.

**Comment by North-West-Wind** [comment]
I've uploaded a new version to CurseForge, which is currently being processed. Test if that solves your problem. If so, close this issue.

By the way, don't report issues with this mod to Mekanism. This is an unofficial plugin and they don't know what I'm doing.

**Comment by Xplodin** [comment]
Awesome job at fixing the issue, sorry for the trouble.
