### ISSUE TITLE
Crash when viewing recipe via fission reactor

### ISSUE THREAD

**Issue by MechOrigin** [North-West-Wind/MekanismFissionRecipe#3]
jei-1.16.5-7.7.1.145
Mekanism-1.16.5-10.1.1.456
MekanismGenerators-1.16.5-10.1.1.456
fissionrecipe-1.1.0-1.16.5.jar

Steps to reproduce:
Upon creating the fission multiblock, I enter the GUI. I hover over the main GUI to "show recipes" and click, and crash.

pastebin of crashlog
https://pastebin.com/raw/xRmYvnUq

**Comment by North-West-Wind** [comment]
This is fixed in the 1.18.2 version. I might backport this to the 1.16.5 version, but I'm closing this now.
I will have you updated if I have updated the 1.16.5 version.
